_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  block_content_permissions: 0
  block_form_alter: 0
  breakpoint: 0
  chosen: 0
  chosen_lib: 0
  ckeditor5: 0
  colorbox: 0
  config: 0
  config_ignore: 0
  config_import_locale: 0
  config_import_single: 0
  config_rewrite: 0
  config_split: 0
  config_translation: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  drimage: 0
  dropsolid_rocketship_drush: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_advanced_link: 0
  environment_indicator: 0
  field: 0
  field_formatter: 0
  field_group: 0
  field_limiter: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  focal_point: 0
  google_tag: 0
  http_cache_control: 0
  image: 0
  image_effects: 0
  imageapi_optimize: 0
  imageapi_optimize_binaries: 0
  imageapi_optimize_resmushit: 0
  inline_entity_form: 0
  language: 0
  layout_builder: 0
  layout_builder_at: 0
  layout_builder_extra_templates: 0
  layout_builder_lock: 0
  layout_builder_modal: 0
  layout_builder_operation_link: 0
  layout_builder_restrictions: 0
  layout_builder_restrictions_by_role: 0
  layout_discovery: 0
  link: 0
  link_attributes: 0
  linkit: 0
  locale: 0
  manage_display: 0
  maxlength: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  menu_clickthrough: 0
  menu_link_content: 0
  menu_trail_by_path: 0
  menu_ui: 0
  metatag: 0
  metatag_async_widget: 0
  metatag_facebook: 0
  metatag_hreflang: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  minifyhtml: 0
  mysql: 0
  node: 0
  node_keep: 0
  node_title_help_text: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  r4032login: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  rocketship_blocks: 0
  rocketship_content: 0
  rocketship_core: 0
  rocketship_page: 0
  rocketship_seo: 0
  role_delegation: 0
  scheduler: 0
  schema_article: 0
  schema_item_list: 0
  schema_metatag: 0
  schema_web_page: 0
  schema_web_site: 0
  search_api: 0
  search_api_db: 0
  seckit: 0
  section_library: 0
  shortcut: 0
  simple_recaptcha: 0
  simple_sitemap: 0
  slick: 0
  slick_ui: 0
  smart_trim: 0
  symfony_mailer: 0
  syslog: 0
  system: 0
  taxonomy: 0
  taxonomy_access_fix: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  userprotect: 0
  video_embed_field: 0
  video_embed_media: 0
  view_unpublished: 0
  webform: 0
  webform_ui: 0
  pathauto: 1
  content_translation: 10
  views: 10
  dropsolid_rocketship_profile: 1000
theme:
  olivero: 0
  claro: 0
profile: dropsolid_rocketship_profile
