_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 59f47a7d-bbc1-46e9-b339-7742f91be80a
name: Drupal
mail: sites@example.com
slogan: ''
page:
  403: /node/4
  404: /node/3
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
